name: Basic Laravel CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Get Code
        uses: actions/checkout@v3

      - name: 2. Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: 3. Install Dependencies
        run: composer install

      - name: 4. Setup App
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: 5. Run Laravel
        run: php artisan --version